# GraphQL configuration.
# The path of GraphQL endpoint for both GET and POST.
path: ${graphql.path:/graphql}
# Path to the websocket endpoint to handle subscription requests.
subscriptionsPath: ${graphql.subscriptionsPath:/subscriptions}
# Enable GraphiQL for development environment only. It allows testing from the Browser.
enableGraphiQL: ${graphql.enableGraphiQL:true}
