# A generic light-4j framework validator configuration. If multiple frameworks are used in the
# same server instance and they have different configurations. You can use graphql-validator.yml
---
# Enable request validation against the specification
enabled: true
# Log error message if validation error occurs
logError: true
